# Configure the fillhole command
settings:
  # Configure filtering selection task
  filter_processed_cycle: 2500000
  filter_tick_cycle: 20

  # Configure searching hole task
  fill_hole_processed_cycle: 100000
  fill_hole_tick_cycle: 30


