# Configure the fillhole command
settings:
  # Configure reload delay, server should be restarted
  reload_delay: 20 * 60 * 5 # 5 minutes

  # Configure max selection size
  max_selection_size: 10000000

  # Configure searching hole task
  fill_hole_processed_cycle: 10000
  fill_hole_tick_cycle: 1

  task_bar_delay: 30
