name: FillHole
author: Nacharon
version: 1.3.1
main: me.nacharon.fillhole.Main
api-version: 1.18
website: https://github.com/LucasT-dev
depend: [ WorldEdit ]

commands:
  fillhole:
    description: Fill the holes in the selection
    usage: /fillhole <pattern>
    aliases: [ fh ]
    permissions:
      fillhole.use:
        description: Allows to use the /fillhole command
        default: op

permissions:
  fillhole.use:
    description: Allows to use the /fillhole command
    default: op