name: FillHole
version: ${version}
main: me.nacharon.fillhole.FillHole
api-version: '1.20.6'
commands:
  fillhole:
    description: Fill the holes in the selection
    usage: /fillhole <pattern>
    aliases: [ fh ]
    permissions:
      fillhole.use:
        description: Allows to use the /fillhole command
        default: op

permissions:
  fillhole.use:
    description: Allows to use the /fillhole command
    default: op