name: FillHole
version: '1.0.11'
main: me.nacharon.fillhole.FillHole
api-version: '1.20.6'
commands:
  fillhole:
    description: Fill the holes in the selection
    usage: /fillhole <pattern>
    aliases: [ fh ]
